apiVersion: v1
kind: Service
metadata:
  name: issuer-postgres
  namespace: gxdch-issuer
spec:
  selector:
    app: issuer-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
