apiVersion: v1
kind: Secret
metadata:
  name: gxdch-issuer-stack
  namespace: gxdch-issuer
type: Opaque
stringData:
  POSTGRES_USER: issuer
  POSTGRES_PASSWORD: issuer
  POSTGRES_DB: issuer
  VAULT_DEV_ROOT_TOKEN_ID: root
  EDC_VAULT_HASHICORP_TOKEN: root
  EDC_IH_API_SUPERUSER_KEY: c3VwZXItdXNlcg==.c3VwZXItc2VjcmV0LWtleQo=
