apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gxdch-issuer
  namespace: argocd
spec:
  description: Dataspace issuer stack for GXDCH
  sourceRepos:
    - https://github.com/Data-Space-Core/GXDCH-Issuer.git
  destinations:
    - namespace: gxdch-issuer
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
